### ISSUE TITLE
Add optional mounting dirs for the docker

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/Hermes#21]
Add an option to mount the current working directory (or other directories) in the docker.sh.

**Comment by jackitg** [comment]
adding CWD makes sense, as to other dirs: is it a constant list you want to be present, or per user stuff? In any case I can  instruct/document how to do it. then in case of constant list, it can be committed, otherwise each user/developer can create a personal  copy of relevant docker and apply it there

**Comment by yehudarav** [comment]
I thought about a command line argument that accepts the path and adding
the CWD

**Comment by jackitg** [comment]
And the destination mount point?

**Comment by yehudarav** [comment]
It could be named 'working directory' and mapped at the home directory of
the user
